server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: 3.1415926mkrgxy
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ConcernService